name: GitHub Readme YouTube Cards
# on:
#   schedule:
#     # Runs every hour, on the hour
#     - cron: '0 * * * *'
#   workflow_dispatch:
on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Youtube
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCyG1GeH1SG6ZqfvNVpVfd5Q
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
      - name: Update Badges
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: juliano-salszbrun
          
